<?php
$sql="
CREATE TABLE `ims_xc_beauty_address` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `mobile` varchar(50) DEFAULT NULL COMMENT '手机号',
  `address` longtext COMMENT '地址',
  `map` longtext COMMENT '地址',
  `content` longtext COMMENT '地址',
  `status` int(11) DEFAULT '-1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`openid`,`status`,`createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='地址';
CREATE TABLE `ims_xc_beauty_article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `content` longtext COMMENT '详情',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `type` int(11) DEFAULT NULL COMMENT '类型（1普通文章2优惠活动文章）',
  `link` varchar(255) DEFAULT NULL COMMENT '链接',
  `btn` varchar(255) DEFAULT NULL COMMENT '按钮文字',
  `link_type` int(11) DEFAULT '1' COMMENT '模式',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='文章';
CREATE TABLE `ims_xc_beauty_banner` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `bimg` varchar(255) DEFAULT NULL COMMENT '图片',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `link` varchar(255) DEFAULT NULL COMMENT '链接',
  `appid` varchar(255) DEFAULT NULL COMMENT '小程序id',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`sort`,`status`,`createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='轮播图';
CREATE TABLE `ims_xc_beauty_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `xkey` varchar(50) DEFAULT NULL COMMENT '关键字',
  `content` longtext COMMENT '内容',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`xkey`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 COMMENT='配置';
CREATE TABLE `ims_xc_beauty_count` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `plan_date` varchar(50) DEFAULT NULL COMMENT '时间',
  `order` int(11) DEFAULT '0' COMMENT '订单量',
  `amount` varchar(50) DEFAULT NULL COMMENT '金额',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `store` int(11) DEFAULT '-1' COMMENT '门店',
  `type` int(11) DEFAULT '1' COMMENT '类型（1月份2日期）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='统计';
CREATE TABLE `ims_xc_beauty_coupon` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '优惠价格',
  `condition` varchar(50) DEFAULT NULL COMMENT '满足条件',
  `times` longtext COMMENT '有效期',
  `total` int(11) DEFAULT '-1' COMMENT '总量',
  `type` int(11) DEFAULT NULL,
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `score` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`sort`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='优惠券';
CREATE TABLE `ims_xc_beauty_discuss` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `pid` int(11) DEFAULT NULL COMMENT '产品id',
  `score` int(11) DEFAULT NULL COMMENT '评价（1满意2一般3不满意）',
  `content` longtext COMMENT '详情',
  `imgs` longtext COMMENT '图片集',
  `tip` int(11) DEFAULT '-1' COMMENT '匿名',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `type` int(11) DEFAULT '1' COMMENT '类型（1服务项目2技师）',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='评论';
CREATE TABLE `ims_xc_beauty_discuss_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `pid` int(11) DEFAULT NULL COMMENT '产品id',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`pid`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='评论日志';
CREATE TABLE `ims_xc_beauty_group` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '团长',
  `pid` int(11) DEFAULT NULL COMMENT '产品id',
  `team` longtext COMMENT '队伍',
  `status` int(11) DEFAULT '-1' COMMENT '状态（-1拼团中1成功2失败）',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `failtime` varchar(50) DEFAULT NULL COMMENT '失败天数',
  `total` int(11) DEFAULT '0' COMMENT '人数',
  `team_total` int(11) DEFAULT '0' COMMENT '团队人数',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`openid`,`pid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='团购';
CREATE TABLE `ims_xc_beauty_moban_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL,
  `nickname` varchar(500) DEFAULT NULL COMMENT '呢称',
  `status` int(11) DEFAULT '-1' COMMENT '-1未使用  1已使用',
  `createtime` int(11) DEFAULT NULL COMMENT '发布日期',
  `ident` varchar(50) DEFAULT NULL COMMENT '标识',
  `headimgurl` varchar(500) DEFAULT NULL COMMENT '头像',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='绑定模版消息用户';
CREATE TABLE `ims_xc_beauty_nav` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `simg` varchar(255) DEFAULT NULL COMMENT '图片',
  `link` varchar(255) DEFAULT NULL COMMENT '链接',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`sort`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自定义导航';
CREATE TABLE `ims_xc_beauty_online` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `store` int(11) DEFAULT NULL COMMENT '门店',
  `plan_date` varchar(50) DEFAULT NULL COMMENT '日期',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预约时间';
CREATE TABLE `ims_xc_beauty_online_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `pid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '发送者用户id',
  `type` int(11) DEFAULT NULL COMMENT '类型1文本2图片',
  `content` longtext COMMENT '内容',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `duty` int(11) DEFAULT '1' COMMENT '身份1客户2客服',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`type`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客服记录';
CREATE TABLE `ims_xc_beauty_onlines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `member` int(11) DEFAULT NULL COMMENT '未读条数',
  `type` int(11) DEFAULT NULL COMMENT '类型',
  `content` longtext COMMENT '内容',
  `updatetime` varchar(50) DEFAULT NULL COMMENT '更新时间',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`createtime`,`member`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客服';
CREATE TABLE `ims_xc_beauty_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `out_trade_no` varchar(50) DEFAULT NULL COMMENT '订单号',
  `wx_out_trade_no` varchar(50) DEFAULT NULL COMMENT '微信订单号',
  `pid` int(11) DEFAULT NULL COMMENT '产品id',
  `kind` varchar(255) DEFAULT NULL COMMENT '种类',
  `total` int(11) DEFAULT NULL COMMENT '数量',
  `plan_date` varchar(50) DEFAULT NULL COMMENT '预约时间',
  `userinfo` longtext COMMENT '用户信息',
  `amount` varchar(50) DEFAULT NULL COMMENT '应付款',
  `o_amount` varchar(50) DEFAULT NULL COMMENT '实付款',
  `status` int(11) DEFAULT '-1' COMMENT '支付状态（-1待支付1已支付2退款',
  `use` int(11) DEFAULT '-1' COMMENT '使用',
  `discuss` int(11) DEFAULT '-1' COMMENT '评论',
  `pay_type` int(11) DEFAULT NULL COMMENT '支付方式（1微信支付2余额支付）',
  `content` longtext COMMENT '备注',
  `coupon_id` int(11) DEFAULT NULL COMMENT '优惠券id',
  `coupon_price` varchar(50) DEFAULT NULL COMMENT '优惠价格',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `form_id` varchar(255) DEFAULT NULL,
  `canpay` varchar(50) DEFAULT NULL COMMENT '余额支付',
  `wxpay` varchar(50) DEFAULT NULL COMMENT '微信支付',
  `refund_content` longtext COMMENT '退款理由',
  `refund_status` int(11) DEFAULT '-1' COMMENT '退款状态',
  `order_type` int(11) DEFAULT '1' COMMENT '1购买2充值3团购',
  `money` varchar(50) DEFAULT NULL COMMENT '钱包',
  `score` int(11) DEFAULT NULL COMMENT '获得积分数',
  `discount` varchar(50) DEFAULT NULL COMMENT '折扣',
  `group` int(11) DEFAULT NULL COMMENT '团购id',
  `one_openid` varchar(50) DEFAULT NULL COMMENT '一级推荐人',
  `one_amount` varchar(50) DEFAULT NULL COMMENT '一级佣金',
  `two_openid` varchar(50) DEFAULT NULL COMMENT '二级推荐人',
  `two_amount` varchar(50) DEFAULT NULL COMMENT '二级佣金',
  `three_openid` varchar(50) DEFAULT NULL COMMENT '三级推荐人',
  `three_amount` varchar(50) DEFAULT NULL COMMENT '三级佣金',
  `store` int(11) DEFAULT NULL COMMENT '门店',
  `member` int(11) DEFAULT NULL COMMENT '店员',
  `gift` varchar(50) DEFAULT NULL COMMENT '赠送金额',
  `charge_id` varchar(255) DEFAULT NULL,
  `service_type` int(11) DEFAULT NULL COMMENT '服务方式（1上门服务2到店服务）',
  `can_use` int(11) DEFAULT '1' COMMENT '使用次数',
  `is_use` int(11) DEFAULT '0' COMMENT '已使用',
  `buy_type` int(11) DEFAULT '1' COMMENT '买单方式（1自助付款2商家待扣）',
  `recharge_type` int(11) DEFAULT '1' COMMENT '充值方式（1会员充值2管理员充值）',
  `recharge_openid` varchar(50) DEFAULT NULL COMMENT '待充的用户id',
  `price` decimal(10,2) DEFAULT NULL COMMENT '单价',
  `flash` int(11) DEFAULT '-1' COMMENT '限时抢购',
  `flash_price` decimal(10,2) DEFAULT NULL COMMENT '抢购价格',
  `failtime` datetime DEFAULT NULL COMMENT '失效时间',
  `failstatus` int(11) DEFAULT '1' COMMENT '失效处理状态',
  `wq_out_trade_no` varchar(50) DEFAULT NULL,
  `he_log` longtext COMMENT '核销记录',
  `can_member` int(11) DEFAULT '1' COMMENT '预约人数',
  `form_id2` varchar(255) DEFAULT NULL,
  `member_discuss` int(11) DEFAULT '-1' COMMENT '人员评论',
  `callback1` longtext COMMENT '短信回调',
  `callback2` longtext COMMENT '打印回调',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`out_trade_no`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单';
CREATE TABLE `ims_xc_beauty_pai` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `midflytime` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='排班';
CREATE TABLE `ims_xc_beauty_pai_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `pid` int(11) DEFAULT NULL,
  `weeknum` int(11) DEFAULT NULL COMMENT '1-7，表示周一到周天',
  `time1start` varchar(50) DEFAULT NULL COMMENT '开始时间',
  `time1end` varchar(50) DEFAULT NULL,
  `time2start` varchar(50) DEFAULT NULL,
  `time2end` varchar(50) DEFAULT NULL,
  `time3start` varchar(50) DEFAULT NULL,
  `time3end` varchar(50) DEFAULT NULL,
  `time4start` varchar(50) DEFAULT NULL,
  `time4end` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`pid`,`status`,`createtime`,`weeknum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='排班详情';
CREATE TABLE `ims_xc_beauty_pick_class` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`sort`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='配货分类';
CREATE TABLE `ims_xc_beauty_pick_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `store` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `out_trade_no` varchar(50) DEFAULT NULL COMMENT '订单号',
  `pid` longtext COMMENT '产品',
  `total` int(11) DEFAULT '0' COMMENT '数量',
  `amount` decimal(10,2) DEFAULT '0.00' COMMENT '总价',
  `status` int(11) DEFAULT '-1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单';
CREATE TABLE `ims_xc_beauty_pick_service` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `cid` int(11) DEFAULT NULL COMMENT '分类',
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `price` decimal(10,2) DEFAULT '0.00' COMMENT '价格',
  `unit` varchar(50) DEFAULT NULL COMMENT '单位',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `cid` (`cid`,`uniacid`,`sort`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='配货';
CREATE TABLE `ims_xc_beauty_prize` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `type` int(11) DEFAULT NULL COMMENT '类型',
  `cid` int(11) DEFAULT NULL COMMENT '优惠券',
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `simg` varchar(255) DEFAULT NULL COMMENT '图片',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `times` int(11) DEFAULT '0' COMMENT '概率',
  `member` int(11) DEFAULT '-1' COMMENT '数量',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`type`,`status`,`sort`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='奖品';
CREATE TABLE `ims_xc_beauty_rotate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `times` int(11) DEFAULT '0' COMMENT '签到次数',
  `plan_date` varchar(50) DEFAULT NULL COMMENT '签到日期',
  `status` int(11) DEFAULT '-1' COMMENT '是否已抽奖',
  `rotated` int(11) DEFAULT '0' COMMENT '抽奖次数',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`openid`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='抽奖';
CREATE TABLE `ims_xc_beauty_rotate_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `pid` int(11) DEFAULT NULL COMMENT '优惠券id',
  `title` varchar(255) DEFAULT NULL COMMENT '标题',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `type` int(11) DEFAULT '1' COMMENT '类型',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `cid` int(11) DEFAULT NULL COMMENT '奖品id',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`openid`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='抽奖记录';
CREATE TABLE `ims_xc_beauty_score` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `title` varchar(50) DEFAULT NULL COMMENT '标题',
  `status` int(11) DEFAULT '1' COMMENT '1获得2消费',
  `score` varchar(50) DEFAULT NULL COMMENT '积分',
  `over` varchar(50) DEFAULT NULL COMMENT '剩余积分',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`openid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='积分记录';
CREATE TABLE `ims_xc_beauty_service` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `cid` int(11) DEFAULT NULL COMMENT '分类',
  `simg` varchar(255) DEFAULT NULL COMMENT '封面',
  `bimg` longtext COMMENT '图片',
  `price` varchar(50) DEFAULT NULL COMMENT '价格',
  `o_price` varchar(50) DEFAULT NULL COMMENT '原价',
  `kind` longtext COMMENT '种类',
  `discuss` int(11) DEFAULT '0' COMMENT '评价总人数',
  `discuss_total` int(11) DEFAULT '0' COMMENT '评价总数',
  `good_total` int(11) DEFAULT '0' COMMENT '满意总数',
  `middle_total` int(11) DEFAULT '0' COMMENT '一般总数',
  `bad_total` int(11) DEFAULT '0' COMMENT '不满意总数',
  `content` longtext COMMENT '详情',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `group_status` int(11) DEFAULT '-1' COMMENT '团购状态',
  `group_price` varchar(50) DEFAULT NULL COMMENT '团购价格',
  `group_total` int(11) DEFAULT '0' COMMENT '团购数',
  `group_limit` int(11) DEFAULT NULL COMMENT '团购限制天数',
  `group_index` int(11) DEFAULT '-1' COMMENT '团购首页显示',
  `group_number` int(11) DEFAULT NULL COMMENT '团购人数',
  `type` int(11) DEFAULT NULL COMMENT '分销方法',
  `level_one` varchar(50) DEFAULT NULL COMMENT '一级分销',
  `level_two` varchar(50) DEFAULT NULL COMMENT '二级分销',
  `level_three` varchar(50) DEFAULT NULL COMMENT '三级分销',
  `store_status` int(11) DEFAULT '1' COMMENT '门店状态',
  `store` longtext COMMENT '适用门店',
  `home` int(11) DEFAULT '1' COMMENT '家',
  `shop` int(11) DEFAULT '1' COMMENT '店',
  `service_time` varchar(50) DEFAULT NULL COMMENT '服务时间',
  `can_use` int(11) DEFAULT '1' COMMENT '核销次数',
  `sold` int(11) DEFAULT '0' COMMENT '已售数',
  `content_type` int(11) DEFAULT '1' COMMENT '详情模式',
  `content2` longtext COMMENT '详情2',
  `parameter` longtext COMMENT '参数',
  `flash_status` int(11) DEFAULT '-1' COMMENT '限时状态',
  `flash_price` decimal(10,2) DEFAULT '0.00' COMMENT '抢购价格',
  `flash_start` datetime DEFAULT NULL COMMENT '开始时间',
  `flash_end` datetime DEFAULT NULL COMMENT '结束时间',
  `flash_member` int(11) DEFAULT NULL COMMENT '库存',
  `flash_index` int(11) DEFAULT '-1' COMMENT '首页显示',
  `flash_order` int(11) DEFAULT '0' COMMENT '每人限买单数',
  `flash_shu` int(11) DEFAULT '0' COMMENT '每单限购数',
  `sale_status` int(11) DEFAULT '-1' COMMENT '折扣状态',
  `group_stock` int(11) DEFAULT '-1' COMMENT '团购库存',
  `group_head_status` int(11) DEFAULT '-1' COMMENT '团长优惠',
  `group_head_price` varchar(50) DEFAULT NULL COMMENT '团长优惠价格',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`cid`,`status`,`sort`,`createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='列表';
CREATE TABLE `ims_xc_beauty_service_class` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `bimg` varchar(255) DEFAULT NULL COMMENT '图片',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `index` int(11) DEFAULT '-1' COMMENT '首页显示',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`sort`,`status`,`createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='分类';
CREATE TABLE `ims_xc_beauty_share` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `title` varchar(255) DEFAULT NULL COMMENT '标题',
  `out_trade_no` varchar(50) DEFAULT NULL COMMENT '订单号',
  `amount` varchar(50) DEFAULT NULL COMMENT '金额',
  `level` int(11) DEFAULT NULL COMMENT '等级',
  `status` int(11) DEFAULT '1' COMMENT '状态（-1等待1成功2失败）',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`openid`,`createtime`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='分销订单';
CREATE TABLE `ims_xc_beauty_shop` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `pid` int(11) DEFAULT NULL COMMENT '产品id',
  `total` int(11) DEFAULT '0' COMMENT '数量',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`pid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='购物车';
CREATE TABLE `ims_xc_beauty_store` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL COMMENT '名称',
  `simg` varchar(255) DEFAULT NULL COMMENT '图标',
  `mobile` varchar(50) DEFAULT NULL COMMENT '手机号',
  `address` longtext COMMENT '地址',
  `map` longtext COMMENT '地址',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `plan_date` varchar(50) DEFAULT NULL COMMENT '营业时间',
  `content` longtext COMMENT '详情',
  `code` varchar(255) DEFAULT NULL COMMENT '买单二维码',
  `sms` varchar(50) DEFAULT NULL COMMENT '短信接收手机号',
  `machine_code` varchar(255) DEFAULT NULL COMMENT '打印机终端号',
  `msign` varchar(255) DEFAULT NULL COMMENT '打印机终端密钥',
  `sn` varchar(255) DEFAULT NULL COMMENT '打印机编号',
  `print_status` int(11) DEFAULT '-1' COMMENT '打印状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COMMENT='门店管理';
CREATE TABLE `ims_xc_beauty_store_member` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `simg` varchar(255) DEFAULT NULL COMMENT '头像',
  `cid` int(11) DEFAULT '0' COMMENT '店面',
  `task` varchar(255) DEFAULT NULL COMMENT '职称',
  `service` longtext COMMENT '服务项目',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `tag` varchar(255) DEFAULT NULL COMMENT '标签',
  `content` longtext COMMENT '个人简介',
  `zan` int(11) DEFAULT '0' COMMENT '点赞人数',
  `discuss` int(11) DEFAULT '0' COMMENT '评论数',
  `pai_status` int(11) DEFAULT '-1' COMMENT '单双周状态',
  `pai1` int(11) DEFAULT NULL COMMENT '排版',
  `pai2` int(11) DEFAULT NULL COMMENT '排版2',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='店员管理';
CREATE TABLE `ims_xc_beauty_store_service` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL COMMENT '名称',
  `price` varchar(50) DEFAULT NULL COMMENT '价格',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `home` int(11) DEFAULT '1' COMMENT '上门服务',
  `shop` int(11) DEFAULT '1' COMMENT '到店服务',
  `can_use` int(11) DEFAULT '1' COMMENT '核销次数',
  `member` varchar(50) DEFAULT NULL COMMENT '抵扣预约人数',
  `sale_status` int(11) DEFAULT '-1' COMMENT '折扣状态',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`sort`,`status`,`createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='门店服务';
CREATE TABLE `ims_xc_beauty_times` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `week` int(11) DEFAULT NULL COMMENT '星期',
  `content` longtext COMMENT '详情',
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预约时间';
CREATE TABLE `ims_xc_beauty_times_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `member` int(11) DEFAULT NULL COMMENT '人员',
  `plan_date` varchar(50) DEFAULT NULL COMMENT '日期',
  `total` int(11) DEFAULT '0' COMMENT '已预约数量',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预约时间记录';
CREATE TABLE `ims_xc_beauty_user_coupon` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `cid` int(11) DEFAULT NULL COMMENT '优惠券id',
  `status` int(11) DEFAULT '-1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户优惠券';
CREATE TABLE `ims_xc_beauty_userinfo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像',
  `nick` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT '1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `money` varchar(50) DEFAULT '0' COMMENT '余额',
  `card` int(11) DEFAULT '-1' COMMENT '会员卡状态（-1未激活1激活）',
  `mobile` varchar(50) DEFAULT NULL COMMENT '手机号',
  `password` varchar(50) DEFAULT NULL COMMENT '支付密码',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `score` int(11) DEFAULT '0' COMMENT '积分',
  `share` varchar(50) DEFAULT NULL COMMENT '推荐人openid',
  `level_one` int(11) DEFAULT '0' COMMENT '一级数量',
  `level_two` int(11) DEFAULT '0' COMMENT '二级数量',
  `level_three` int(11) DEFAULT '0' COMMENT '三级数量',
  `share_amount` varchar(50) DEFAULT '0' COMMENT '累计佣金',
  `share_o_amount` varchar(50) DEFAULT '0' COMMENT '可提现佣金',
  `share_t_amount` varchar(50) DEFAULT '0' COMMENT '已提现佣金',
  `share_empty` varchar(50) DEFAULT '0' COMMENT '无效佣金',
  `shop` int(11) DEFAULT '-1' COMMENT '店铺管理',
  `store` int(11) DEFAULT NULL COMMENT '绑定门店',
  `shop_id` int(11) DEFAULT NULL COMMENT '子管理员门店id',
  `card_name` varchar(50) DEFAULT NULL COMMENT '会员等级',
  `card_price` varchar(50) DEFAULT NULL COMMENT '会员折扣',
  `card_amount` decimal(10,2) DEFAULT '0.00' COMMENT '消费金额',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`status`,`createtime`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8 COMMENT='用户信息';
CREATE TABLE `ims_xc_beauty_withdraw` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `pay_type` int(11) DEFAULT '1' COMMENT '提现方式（1微信2支付宝）',
  `username` varchar(50) DEFAULT NULL COMMENT '账号',
  `mobile` varchar(50) DEFAULT NULL COMMENT '手机号',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `amount` varchar(50) DEFAULT NULL COMMENT '金额',
  `money` varchar(50) DEFAULT NULL COMMENT '余额',
  `status` int(11) DEFAULT '-1' COMMENT '状态（-1待处理1成功2失败）',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `order_type` int(11) DEFAULT '1' COMMENT '提现类型(1余额提现2佣金提现)',
  `out_trade_no` varchar(50) DEFAULT NULL COMMENT '订单号',
  `wx_out_trade_no` varchar(50) DEFAULT NULL COMMENT '微信订单号',
  `content` longtext COMMENT '错误详情',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`openid`,`createtime`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='提现申请';
CREATE TABLE `ims_xc_beauty_zan` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(50) DEFAULT NULL COMMENT '用户id',
  `pid` int(11) DEFAULT NULL COMMENT '技师id',
  `status` int(11) DEFAULT '-1' COMMENT '状态',
  `createtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`id`),
  KEY `uniacid` (`uniacid`,`pid`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='点赞记录';
";
pdo_run($sql);
?>